#!/bin/bash
# ####################################################################
# script: build-pilomar
# Save as UNIX file.
# 5.Dec.2023 / Rasbian Bookworm
# ####################################################################

echo -e
echo -e
echo -e
# Get system information
source ./system-info

echo -e
curUser=$(whoami)
echo "You are currently logged in as: $curUser"
echo -e
export observatory='/home/'$curUser'/pilomar'
echo "Home directory is set to: $observatory"
echo -e

# list current packages and versions.
#echo Initial packages installed>>$observatory/log/buildpilomar
#echo - dpkg list:----------------------------------------------
#dpkg-query -l>>$observatory/log/buildpilomar
#echo - pip3 list:----------------------------------------------
#pip3 list>>$observatory/log/buildpilomar
#echo - apt list:-----------------------------------------------
#apt list --installed>>$observatory/log/buildpilomar
#echo ----------------------------------------------------------

# Log start of the script (AFTER checking that the target directory exists)
#sudo chmod 777 $observatory/log
#echo $(date) buildpilomar script start >> $observatory/log/buildpilomar

echo -e "==========================================================="
echo -e "\E[36;40mGeneral System Update...\E[0m"
#echo $(date) General System Update >> $observatory/log/buildpilomar
# Update and upgrade the package directories
sudo apt update && sudo apt upgrade -y
echo -e

# Install all apt packages needed
sudo apt install python3 pip zip libwebp-dev libtiff6 libopenjp2-7-dev libjasper-dev libqtgui4 libqt4-test libhdf5-dev imutils libilmbase23 libopenexr-dev libavcodec-dev libavformat-dev libswscale-dev libv4l-dev libatlas-base-dev python3-opencv -y

echo -e
# Install required Python libraries
sudo pip3 install -r ../src/requirements.txt


echo -e
echo Cleanup apt-get space. 
sudo apt autoremove
sudo apt-get clean

echo -e
#echo Final packages installed >> $observatory/log/buildpilomar
echo - dpkg list:----------------------------------------------
#dpkg-query -l >> $observatory/log/buildpilomar
echo - pip3 list:----------------------------------------------
#pip3 list >> $observatory/log/buildpilomar
echo - apt list:-----------------------------------------------
#apt list --installed >> $observatory/log/buildpilomar
echo ----------------------------------------------------------

#echo $(date) buildpilomar script end >> $observatory/log/buildpilomar

echo
echo -e "***********************************************************************************************************************"
echo -e "For PILOMAR you must also enable VNC, CAMERA, SSH and SERIAL PORT (but disable console to serial port) via raspi-config"
echo -e "***********************************************************************************************************************"

echo -e "\E[32;40m------------------------------\E[0m"
echo -e "\E[32;40mBuild complete. Please reboot.\E[0m"
echo -e "\E[32;40m------------------------------\E[0m"
exit