#!/bin/bash
# ####################################################################
# script: build-pilomar
# Save as UNIX file.
# 5.Dec.2023 / Rasbian Bookworm
# ####################################################################


# Get system information
source ./system-info

echo -e
curUser=$(whoami)
echo "You are currently logged in as: $curUser"
echo -e
export observatory='/home/$curUser/pilomar'
echo home directory is: $observatory
echo -e

# list current packages and versions.
#echo Initial packages installed>>$observatory/log/buildpilomar
#echo - dpkg list:----------------------------------------------
#dpkg-query -l>>$observatory/log/buildpilomar
#echo - pip3 list:----------------------------------------------
#pip3 list>>$observatory/log/buildpilomar
#echo - apt list:-----------------------------------------------
#apt list --installed>>$observatory/log/buildpilomar
#echo ----------------------------------------------------------