#!/bin/bash
# ####################################################################
# script: system-info
# Show system information
# 13.Dec.2023 / Rasbian Bookworm
# ####################################################################

# Get the hostname
hostname=$(hostname)

# Debian Version
version=$(. /etc/os-release; echo $PRETTY_NAME)

# Get the kernel version
kernel_version=$(uname -r)

# Get the uptime
uptime=$(uptime)

# Print the system information
echo "Hostname: $hostname"
echo "System Version: $version"
echo "Kernel version: $kernel_version"
echo "Uptime: $uptime"