#!/bin/bash
# ####################################################################
# script: system-info
# Show system information
# 13.Dec.2023 / Rasbian Bookworm
# ####################################################################

# Get the hostname
hostname=$(hostname)

# Get the uptime
uptime=$(uptime)

# Get the kernel version
kernel_version=$(uname -r)

# Print the system information
echo "Hostname: $hostname"
echo "Uptime: $uptime"
echo "Kernel version: $kernel_version"